export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"e":"<h1> 介绍页</h1>\n<p>将你的个人介绍和档案放置在此处。</p>\n","y":"a","t":"介绍页","i":"info","I":1},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"首页","i":"home","I":1},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"幻灯片页","i":"slides","I":1},["/slides","/slides.md"]],
  ["v-653b81a3","/arithmetic/bessel.html",{"d":"2022-01-01T00:00:00.000Z","l":"2022年1月1日","c":["可视化项目"],"g":["threejs","vue","maptalks"],"e":"<h1> 贝塞尔</h1>\n<h2> 项目背景</h2>\n<p>这里是项目背景内容。</p>\n<h2> 项目开发过程</h2>\n<h2> 技术要点</h2>\n<h2> 项目总结</h2>\n<h2> 展示</h2>\n","y":"a","t":"贝塞尔","i":"edit","I":1},["/arithmetic/bessel","/arithmetic/bessel.md"]],
  ["v-f510f7a8","/arithmetic/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li><a href=\"/arithmetic/bessel.html\" target=\"blank\">贝塞尔曲线</a></li>\n</ul>\n","y":"a","t":"算法","i":"calculate","I":1},["/arithmetic/index.html","/arithmetic/README.md"]],
  ["v-5aa3d8ba","/en/intro.html",{"e":"<h1> Intro Page</h1>\n<p>Place your introduction and profile here.</p>\n","y":"a","t":"Intro Page","i":"info","I":1},["/en/intro","/en/intro.md"]],
  ["v-2d0a870d","/en/",{"y":"h","t":"Blog Home","i":"home","I":1},["/en/index.html","/en/README.md"]],
  ["v-367b840a","/en/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"Slide page","i":"slides","I":1},["/en/slides","/en/slides.md"]],
  ["v-63f88b46","/project/gistopo.html",{"d":"2022-01-01T00:00:00.000Z","l":"2022年1月1日","c":["可视化项目"],"g":["threejs","vue","maptalks"],"e":"<h1> 基于gis的网络拓扑视图</h1>\n<h2> 项目背景</h2>\n<p>这里是项目背景内容。</p>\n<h2> 项目开发过程</h2>\n<h2> 技术要点</h2>\n<h2> 项目总结</h2>\n<h2> 展示</h2>\n","y":"a","t":"基于gis的网络拓扑视图","i":"edit","I":1},["/project/gistopo","/project/gistopo.md"]],
  ["v-c9bbfba2","/project/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li><a href=\"/project/gistopo.html\" target=\"blank\">基于gis的网络拓扑视图</a></li>\n</ul>\n","y":"a","t":"项目","i":"discover","I":1},["/project/index.html","/project/README.md"]],
  ["v-df57e292","/en/arithmetic/bessel.html",{"d":"2022-01-01T00:00:00.000Z","l":"January 1, 2022","c":["可视化项目"],"g":["threejs","vue","maptalks"],"e":"<h1> 贝塞尔</h1>\n<h2> 项目背景</h2>\n<p>这里是项目背景内容。</p>\n<h2> 项目开发过程</h2>\n<h2> 技术要点</h2>\n<h2> 项目总结</h2>\n<h2> 展示</h2>\n","y":"a","t":"贝塞尔","i":"edit","I":1},["/en/arithmetic/bessel","/en/arithmetic/bessel.md"]],
  ["v-e49748d0","/en/arithmetic/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li><a href=\"/en/arithmetic/bessel.html\" target=\"blank\">贝塞尔曲线</a></li>\n</ul>\n","y":"a","t":"算法","i":"calculate","I":1},["/en/arithmetic/index.html","/en/arithmetic/README.md"]],
  ["v-06447c71","/en/project/gistopo.html",{"d":"2022-01-01T00:00:00.000Z","l":"January 1, 2022","c":["可视化项目"],"g":["threejs","vue","maptalks"],"e":"<h1> 基于gis的网络拓扑视图</h1>\n<h2> 项目背景</h2>\n<p>这里是项目背景内容。</p>\n<h2> 项目开发过程</h2>\n<h2> 技术要点</h2>\n<h2> 项目总结</h2>\n<h2> 展示</h2>\n","y":"a","t":"基于gis的网络拓扑视图","i":"edit","I":1},["/en/project/gistopo","/en/project/gistopo.md"]],
  ["v-34f37b7a","/en/project/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li><a href=\"/en/project/gistopo.html\" target=\"blank\">基于gis的网络拓扑视图</a></li>\n</ul>\n","y":"a","t":"项目","i":"discover","I":1},["/en/project/index.html","/en/project/README.md"]],
  ["v-5d24ec26","/stady/nodejs/node.html",{"d":"2022-01-01T00:00:00.000Z","l":"2022年1月1日","c":["前端"],"g":["node","nodejs"],"e":"<h1> node</h1>\n<h2> 包管理工具</h2>\n<p>这里是内容。</p>\n<h3> npm</h3>\n<p>通过npm可以更好的管理自己的工具包，其他人也可以更好的使用我们的工具包。</p>\n<p>包管理工具npm:Node Package Manager,也就是Node包管理器；</p>\n<p>但是目前已经不仅仅是Nod包管理器了，在前端项目中我们也在使用它来管理依赖的包：比如express、koa、react、.react-dom、axios、.babel、webpack等等；</p>\n<h3> 配置项</h3>\n<p>配置文件记录该项目的名称、版本号、项目描述；\n记录项目所使用其他项目的的依赖名称、版本号；\n配置文件无论是前端还是后端都是是package.json文件。</p>","y":"a","t":"node","i":"edit","I":1},["/stady/nodejs/node","/stady/nodejs/node.md"]],
  ["v-71d1fb11","/stady/nodejs/",{"c":["前端"],"e":"<h1> 目录</h1>\n<ul>\n<li><a href=\"/stady/nodejs/node.html\" target=\"blank\">node</a></li>\n</ul>\n","y":"a","t":"nodejs","i":"nodeJS","I":1},["/stady/nodejs/index.html","/stady/nodejs/README.md"]],
  ["v-29199fe6","/stady/threejs/base.html",{"d":"2022-01-01T00:00:00.000Z","l":"2022年1月1日","c":["苹果"],"g":["红","大","圆"],"e":"<h1> threejs基础</h1>\n<h2> 标题 2</h2>\n<p>这里是内容。</p>\n<h3> 标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"threejs基础","i":"edit","I":1},["/stady/threejs/base","/stady/threejs/base.md"]],
  ["v-f2e0f19a","/stady/threejs/base2.html",{"d":"2022-01-01T00:00:00.000Z","l":"2022年1月1日","c":["苹果"],"g":["红","大","圆"],"e":"<h1> threejs基础2</h1>\n<h2> 标题 2</h2>\n<p>这里是内容。</p>\n<h3> 标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"threejs基础2","i":"edit","I":1},["/stady/threejs/base2","/stady/threejs/base2.md"]],
  ["v-ef850d8c","/en/stady/nodejs/node.html",{"d":"2022-01-01T00:00:00.000Z","l":"January 1, 2022","c":["前端"],"g":["node","nodejs"],"e":"<h1> node</h1>\n<h2> 包管理工具</h2>\n<p>这里是内容。</p>\n<h3> npm</h3>\n<p>通过npm可以更好的管理自己的工具包，其他人也可以更好的使用我们的工具包。</p>\n<p>包管理工具npm:Node Package Manager,也就是Node包管理器；</p>\n<p>但是目前已经不仅仅是Nod包管理器了，在前端项目中我们也在使用它来管理依赖的包：比如express、koa、react、.react-dom、axios、.babel、webpack等等；</p>\n<h3> 配置项</h3>\n<p>配置文件记录该项目的名称、版本号、项目描述。</p>\n","y":"a","t":"node","i":"edit","I":1},["/en/stady/nodejs/node","/en/stady/nodejs/node.md"]],
  ["v-236c4579","/en/stady/threejs/base.html",{"d":"2022-01-01T00:00:00.000Z","l":"January 1, 2022","c":["苹果"],"g":["红","大","圆"],"e":"<h1> threejs基础</h1>\n<h2> 标题 2</h2>\n<p>这里是内容。</p>\n<h3> 标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"threejs基础","i":"edit","I":1},["/en/stady/threejs/base","/en/stady/threejs/base.md"]],
  ["v-4db91f47","/en/stady/threejs/base2.html",{"d":"2022-01-01T00:00:00.000Z","l":"January 1, 2022","c":["苹果"],"g":["红","大","圆"],"e":"<h1> threejs基础2</h1>\n<h2> 标题 2</h2>\n<p>这里是内容。</p>\n<h3> 标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"threejs基础2","i":"edit","I":1},["/en/stady/threejs/base2","/en/stady/threejs/base2.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":"","I":1},["/404"]],
  ["v-d72aaf5a","/stady/",{"y":"p","t":"Stady","I":1},["/stady/index.html"]],
  ["v-456b620a","/stady/threejs/",{"y":"p","t":"Threejs","I":1},["/stady/threejs/index.html"]],
  ["v-5e36a77d","/en/stady/nodejs/",{"y":"p","t":"Nodejs","I":1},["/en/stady/nodejs/index.html"]],
  ["v-bd704532","/en/stady/",{"y":"p","t":"Stady","I":1},["/en/stady/index.html"]],
  ["v-7d7b300f","/en/stady/threejs/",{"y":"p","t":"Threejs","I":1},["/en/stady/threejs/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":1},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":1},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":1},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":1},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":1},["/timeline/index.html"]],
  ["v-9830847c","/category/%E5%8F%AF%E8%A7%86%E5%8C%96%E9%A1%B9%E7%9B%AE/",{"y":"p","t":"可视化项目 分类","I":1},["/category/可视化项目/","/category/%E5%8F%AF%E8%A7%86%E5%8C%96%E9%A1%B9%E7%9B%AE/index.html"]],
  ["v-36470414","/tag/threejs/",{"y":"p","t":"threejs 标签","I":1},["/tag/threejs/index.html"]],
  ["v-506407f4","/en/article/",{"y":"p","t":"Articles","I":1},["/en/article/index.html"]],
  ["v-37a8c5a0","/en/star/",{"y":"p","t":"Star","I":1},["/en/star/index.html"]],
  ["v-0379cba1","/en/timeline/",{"y":"p","t":"Timeline","I":1},["/en/timeline/index.html"]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"使用指南 分类","I":1},["/category/使用指南/","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/index.html"]],
  ["v-b302da92","/tag/vue/",{"y":"p","t":"vue 标签","I":1},["/tag/vue/index.html"]],
  ["v-e9c7e408","/category/%E5%89%8D%E7%AB%AF/",{"y":"p","t":"前端 分类","I":1},["/category/前端/","/category/%E5%89%8D%E7%AB%AF/index.html"]],
  ["v-fd7ea4d4","/tag/maptalks/",{"y":"p","t":"maptalks 标签","I":1},["/tag/maptalks/index.html"]],
  ["v-40b68770","/category/%E8%8B%B9%E6%9E%9C/",{"y":"p","t":"苹果 分类","I":1},["/category/苹果/","/category/%E8%8B%B9%E6%9E%9C/index.html"]],
  ["v-28e050df","/tag/node/",{"y":"p","t":"node 标签","I":1},["/tag/node/index.html"]],
  ["v-5decfa84","/en/category/",{"y":"p","t":"Category","I":1},["/en/category/index.html"]],
  ["v-721080b6","/tag/nodejs/",{"y":"p","t":"nodejs 标签","I":1},["/tag/nodejs/index.html"]],
  ["v-dd5fb9a4","/en/category/%E5%8F%AF%E8%A7%86%E5%8C%96%E9%A1%B9%E7%9B%AE/",{"y":"p","t":"可视化项目 Category","I":1},["/en/category/可视化项目/","/en/category/%E5%8F%AF%E8%A7%86%E5%8C%96%E9%A1%B9%E7%9B%AE/index.html"]],
  ["v-0f1d0e94","/tag/%E7%BA%A2/",{"y":"p","t":"红 标签","I":1},["/tag/红/","/tag/%E7%BA%A2/index.html"]],
  ["v-4f5cd751","/en/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"使用指南 Category","I":1},["/en/category/使用指南/","/en/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/index.html"]],
  ["v-3ceeab45","/tag/%E5%A4%A7/",{"y":"p","t":"大 标签","I":1},["/tag/大/","/tag/%E5%A4%A7/index.html"]],
  ["v-165907e0","/en/category/%E5%89%8D%E7%AB%AF/",{"y":"p","t":"前端 Category","I":1},["/en/category/前端/","/en/category/%E5%89%8D%E7%AB%AF/index.html"]],
  ["v-301b24f4","/tag/%E5%9C%86/",{"y":"p","t":"圆 标签","I":1},["/tag/圆/","/tag/%E5%9C%86/index.html"]],
  ["v-495c2a5c","/en/category/%E8%8B%B9%E6%9E%9C/",{"y":"p","t":"苹果 Category","I":1},["/en/category/苹果/","/en/category/%E8%8B%B9%E6%9E%9C/index.html"]],
  ["v-075c6c62","/en/tag/",{"y":"p","t":"Tag","I":1},["/en/tag/index.html"]],
  ["v-378ad7ec","/en/tag/threejs/",{"y":"p","t":"threejs Tag","I":1},["/en/tag/threejs/index.html"]],
  ["v-1e3a5a6a","/en/tag/vue/",{"y":"p","t":"vue Tag","I":1},["/en/tag/vue/index.html"]],
  ["v-6da55a02","/en/tag/maptalks/",{"y":"p","t":"maptalks Tag","I":1},["/en/tag/maptalks/index.html"]],
  ["v-2b04134b","/en/tag/node/",{"y":"p","t":"node Tag","I":1},["/en/tag/node/index.html"]],
  ["v-7a4d5822","/en/tag/nodejs/",{"y":"p","t":"nodejs Tag","I":1},["/en/tag/nodejs/index.html"]],
  ["v-a16420b0","/en/tag/%E7%BA%A2/",{"y":"p","t":"红 Tag","I":1},["/en/tag/红/","/en/tag/%E7%BA%A2/index.html"]],
  ["v-45c0e74e","/en/tag/%E5%A4%A7/",{"y":"p","t":"大 Tag","I":1},["/en/tag/大/","/en/tag/%E5%A4%A7/index.html"]],
  ["v-5f67f3f0","/en/tag/%E5%9C%86/",{"y":"p","t":"圆 Tag","I":1},["/en/tag/圆/","/en/tag/%E5%9C%86/index.html"]],
]
